# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  IMAGE: 127.0.0.1/hello-world-demo
  IMAGE_TAG: local
  KUBECONFIG: '{{.TASKFILE_DIR}}/.kubeconfig'

tasks:
  pip-install:
    vars:
      REQUIREMENTS: '{{default "dev-requirements.txt" .REQUIREMENTS}}'
    cmds:
      - pip install -q --require-virtualenv --disable-pip-version-check -r dev-requirements.txt -r "{{.REQUIREMENTS}}"
    silent: true

  python-test:
    desc: Lint and test Python code
    deps: [pip-install]
    cmds:
      - pycodestyle src/
      - pytest

  build-image:
    desc: Build Container image
    deps: [minikube-launch]
    cmds:
      - minikube image build -t {{.IMAGE}}:{{.IMAGE_TAG}} {{.TASKFILE_DIR}}

  minikube-launch:
    desc: Launch Minikube cluster with Docker driver
    cmds:
      - minikube start
      - minikube addons enable ingress
    status:
      - minikube status

  minikube-helloworld-deploy:
    desc: Deploy Hello World App using minikube
    deps: [build-image]
    cmds:
      - minikube kubectl -- apply -f '{{.TASKFILE_DIR}}/static-deploy.yaml'
      - |
        echo "Site is available : "
        echo $(minikube service -n ingress-nginx ingress-nginx-controller --url | head -1)
        echo
        echo "Note - HTTP 'Host' must be 'static-hello.localdomain' when making the request"

  helm-install:
    desc: Deploy Hello World app using Helm
    deps: [build-image]
    env:
      KUBECONFIG: '{{.KUBECONFIG}}'
    cmds:
      - minikube update-context
      - |
        helm upgrade --install \
          -n hello-world \
          --create-namespace \
          -f helm/hello-world/deploy-values.yaml \
          hello-world \
          helm/hello-world/
      - |
        echo "Site is available : "
        echo $(minikube service -n ingress-nginx ingress-nginx-controller --url | head -1)
        echo
        echo "Note - HTTP 'Host' must be 'hello.localdomain' when making the request"

  default:
    cmds:
      - task: minikube-launch
      - task: helm-install
    silent: true
